name: CI Pipeline - Linux

on:
  push:
    branches: ["**"]

jobs:
   test:
    name: Build & Test - Ubuntu
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v4

      - &setup-dependencies
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - &setup-vcpkg
        name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - &configure-build
        name: Configure
        run: cmake --preset release

      - &build
        name: Build
        run: cmake --build --preset release

      - &test
        name: Test
        run: ctest --preset release --output-on-failure