name: CI Pipeline for Linux

on:
  push:
    branches: ["**"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
   test:
    name: Build & Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v6

      - &setup-dependencies
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxi-dev \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - &setup-vcpkg
        name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - &configure
        name: Configure
        run: cmake --preset release

      - &build
        name: Build
        run: cmake --build --preset release

      - &test
        name: Test
        run: ctest --preset release --output-on-failure