name: CI Pipeline for Linux

on:
  push:
    branches: ["**"]

jobs:
  tests:
    name: Build & Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v6

      - &setup-dependencies
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxi-dev \
            libxrandr-dev \
            libxcursor-dev \
            libudev-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - &setup-vcpkg
        name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - &configure
        name: Configure
        run: cmake --preset release

      - &build
        name: Build
        run: cmake --build --preset release

      - &test
        name: Test
        run: ctest --preset release --output-on-failure --no-tests=error

  coverage:
    name: Code Coverage on Ubuntu
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - *checkout
      - *setup-dependencies

      - name: Install gcovr
        run: sudo apt-get install -y gcovr

      - *setup-vcpkg

      - name: Configure with coverage flags
        run: cmake --preset coverage

      - name: Build with coverage flags
        run: cmake --build --preset coverage

      - name: Run tests with coverage flags
        run: ctest --preset coverage --output-on-failure --no-tests=error

      - name: Generate coverage report
        run: |
          gcovr \
            --root . \
            --filter '^(src|include)/' \
            --exclude '^(tests|build|include/ui|src/ui)/' \
            --html-details coverage.html \
            --xml coverage.xml \
            --exclude-unreachable-branches \
            --exclude-throw-branches

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml     # Upload the gcovr-generated report from previous step.
          disable_search: true    # Prevent codecov from auto-discovering additional coverage files in the workspace.
          plugins: noop           # Disable all plugins (e.g. gcov). We already generate a filtered coverage report via gcovr, so no additional coverage collection should run.
          fail_ci_if_error: true  # Fail the workflow if the upload to codecov fails.

  clang-format-check:
    name: Clang-Format Check on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - *checkout
      
      - name: Clang-Format Check
        uses: RafikFarhad/clang-format-github-action@v6
        id: clang-format
        with:
          style: file
          sources: "*.cpp,*.hpp,*.h,*.c"

  clang-tidy-check:
    name: Clang-Tidy Check on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - *checkout
      - *setup-dependencies

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy-20

      - *setup-vcpkg

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug

      - name: Run clang-tidy checks
        run: run-clang-tidy-20 -p build/debug -config-file .clang-tidy
      
      