name: CI Pipeline for Windows

on:
  push:
    branches: ["**"]

jobs:
  windows:
    name: Build & Test on Windows
    runs-on: windows-latest

    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@v6

      - &setup-msvc
        name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - &setup-vcpkg
        name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - &configure
        name: Configure
        run: cmake --preset debug

      - &build
        name: Build
        run: cmake --build --preset debug

      - &test
        name: Test
        run: ctest ctest --preset release --output-on-failure